### ISSUE TITLE
Very laggy when checking production statistic panel with Bottleneck mod

### ISSUE THREAD

**Issue by jessefjxm** [Velociraptor115-DSPModding/Blackbox#13]
If I install both Blackbox mod & Bottleneck mod, and open the Production Statistic panel, my fps will drop below 20fps immediatly. If I close the panel, fps goes back.
Following panel face same lag issue:
· Production Statistic
· Electricity Statistic
· Research Statistic
· Dyson Sphere
This happens whether Blackbox mod is analysing or not.
Disable any one of them can fix this problem. But both of you are too amazing to drop!

**Comment by Velociraptor115** [comment]
~~Have you checked that the issue does not occur with each of the mods individually?~~
~~If you're using a mod manager, you can temporarily disable a mod and check~~
Sorry, my bad, skimmed over the first part of the last line. Just reread the post
I will look into this
If you are on Discord, you can ping raptor115 on the DSP server's #modding channel

**Comment by jessefjxm** [comment]
> Have you checked that the issue does not occur with each of the mods individually? If you're using a mod manager, you can temporarily disable a mod and check

Yes, i tried disabled Blackbox & keep Bottleneck first, then disable Bottleneck & keep Blackbox. 
Lag disappear on both attempt.

**Comment by Velociraptor115** [comment]
If you are on Discord, you can ping `raptor115` on the DSP server's #modding channel

**Comment by Velociraptor115** [comment]
I will look into this

**Comment by Velociraptor115** [comment]
If you are able to get BepInEx logs and post them here, it will help speed up figuring out what the issue exactly is

**Comment by Velociraptor115** [comment]
If possible, can you share the following?
It will help identify and resolve the issue faster

* your mod list
* your PC specs
* your fps before opening stats panel with both Bottleneck and Blackbox installed
* if possible, a screenshot of your performance panel during regular play
* if possible, the BepInEx logs when the stats panel is being opened

**Comment by jessefjxm** [comment]
Hi, I just created a new mod profile trying to reproduce this issue with minimal mods, starting with only Bottlenck + Blackbox.
But strangely lag disappear this time, even after I re-install all the mods back. Maybe some mods not update as expected before?
I'll take some further test.

**Comment by jessefjxm** [comment]
I feel lilke it's a pure Bottleneck mod issue as it become laggy when i switch into [full galaxy statistic] mod.

**Comment by Velociraptor115** [comment]
I see
We'll see whether we can optimize Bottleneck's stats collection
